name: Start workflow
on: 
  push:
  workflow_dispatch:
jobs:
  Up-All:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Apt update
        run: 'sudo apt update'
      - name: Install requirements
        run: 'sudo pip install -r requirements.txt'
      - name: Install request library
        run: 'apt update && sudo pip install request'
      
