name: Start workflow
on: 
  push:
  workflow_dispatch:
jobs:
  Up-All:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v4
        with:
         ref: main
      - name: Install dependencies
        run: 'npm install --legacy-peer-deps'
      - name: Build project
        run: 'npm build'
